version: "3"

services:
    influxdb:
        build: ./influxdb
        container_name: influxdb
        ports:
            - "8086:8086"
        volumes:
            - ./influxdb/data:/var/lib/influxdb
        restart: unless-stopped      
    grafana:
        image: grafana/grafana
        container_name: grafana
        ports: 
            - "3000:3000"
        links:
            - influxdb
        volumes:
            - /var/lib/grafana
            - /var/log/grafana
        restart: unless-stopped